# Generated by Django 3.2 on 2021-10-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(max_length=50)),
                ('thumbnail', models.URLField()),
                ('author', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='laptop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
